# Generated by Django 5.1.7 on 2025-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dietplan',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='exerciseplan',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='healthlog',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='healthprofile',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chat',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
