# Generated by Django 5.1.7 on 2025-05-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_chat_options_alter_dietplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='is_active',
        ),
    ]
