# Generated by Django 5.1.7 on 2025-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_remove_reminder_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='image',
            field=models.ImageField(null=True, upload_to='diet/%Y/%m/'),
        ),
    ]
