# Generated by Django 5.1.7 on 2025-05-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_dietplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='user/%Y/%m/'),
        ),
    ]
